### ISSUE TITLE
是否支持idea13版本，是否兼容 jdk7

### ISSUE THREAD

**Issue by kkrgwbj** [wuzhizhan/free-idea-mybatis#12]
我在13版本上，使用进去报错了。提示好像不兼容jdk8以下的错误。是否支持jdk7呢？

**Comment by wuzhizhan** [comment]
@kkrgwbj  idea13版本可能不支持，没测试过。jdk7是支持的。

**Comment by wuzhizhan** [comment]
最新版本只支持从2016.1开始，不打算支持太旧的版本了
