### ISSUE TITLE
在xml提示parm的时候出错

### ISSUE THREAD

**Issue by 1409070209** [wuzhizhan/free-idea-mybatis#17]
使用#{
然后提示param发现idea抛出异常

![image](https://user-images.githubusercontent.com/17427480/32209726-bb9636e0-be44-11e7-8a92-bf597d7d5a17.png)

**Comment by wuzhizhan** [comment]
你的版本是哪个呢？好像2017.3会有这个问题。我这里用2017.2正常

**Comment by 1409070209** [comment]
不好意思啊先生。现在插件的运行正常了。不知为何

**Comment by wuzhizhan** [comment]
真的有这个bug,现在修复了。可以更新
