### ISSUE TITLE
自动创建resultMap

### ISSUE THREAD

**Issue by wuzhizhan** [wuzhizhan/free-idea-mybatis#2]
根据bean产生resultMap

**Comment by wangcansunking** [comment]
how to generate the mapper xml with this plugin?

**Comment by wuzhizhan** [comment]
@wangcansunking move the cursor to the mapper interface ,then press  alt+enter ,select 
【generate mapper of xml]

**Comment by neesonqk** [comment]
@wuzhizhan which is not working with Mac version. option/alt doesn't trigger any context menu.

**Comment by wuzhizhan** [comment]
@neesonqk  这个问题好抱歉,没有高大上的mac可以用来测试.
