### ISSUE TITLE
跳转的图标

### ISSUE THREAD

**Issue by MisterDeng** [wuzhizhan/free-idea-mybatis#22]
能换个清新的点的图标吗？影响idea美观啊

**Comment by MisterDeng** [comment]
![image](https://user-images.githubusercontent.com/12538286/34284657-a1ee2be2-e70e-11e7-9f56-8a5ef0048d2a.png)

**Comment by MisterDeng** [comment]
mapper的java文件莫名其妙就报错
![image](https://user-images.githubusercontent.com/12538286/34286578-83d4dc10-e71c-11e7-9c4d-b5c10bc5df63.png)
![image](https://user-images.githubusercontent.com/12538286/34286581-8d278574-e71c-11e7-8f4d-5f60949702ad.png)

**Comment by wuzhizhan** [comment]
抽时间搞一下这两个问题

**Comment by venbill** [comment]
hello,如果把前面这个图标去掉就好了，直接ctrl+左击方法名跳转

**Comment by wuzhizhan** [comment]
@venbill  我还是希望有个标记，能够看出来是否有跳转效果。像spring自动有这些
![image](https://user-images.githubusercontent.com/2205544/34705988-51a9d64c-f53f-11e7-82c5-4a150df72371.png)

**Comment by MisterDeng** [comment]
我自己换了一下，把images换了重新打包一下

**Comment by 7polo** [comment]
确实有点影响美观，希望能换一下

**Comment by wuzhizhan** [comment]
@MisterDeng  是否能交个pullrequest来，我自己设计不来这个东西

**Comment by yksoul** [comment]
可以去阿里巴巴图标库，找下合适的图标。
