### ISSUE TITLE
resultType="java.util.LinkedHashMap" mapper接口报错？

### ISSUE THREAD

**Issue by claer-ding** [wuzhizhan/free-idea-mybatis#27]
![_20180127151205](https://user-images.githubusercontent.com/30252550/35469661-affa35f0-0374-11e8-959a-fdb0668fc579.png)
![_20180127151225](https://user-images.githubusercontent.com/30252550/35469662-b0f9d21c-0374-11e8-9655-42a7979ef6ca.png)

**Comment by lppedd** [comment]
Hi @claer-ding 
I will give this a look today and hopefully by the end of the they I'll publish a pull request

**Comment by wuzhizhan** [comment]
fix
