### ISSUE TITLE
用的是idea15.0.6这个插件用不了麻烦帮我看看

### ISSUE THREAD

**Issue by ElliottNing** [wuzhizhan/free-idea-mybatis#29]
![_20180223152003](https://user-images.githubusercontent.com/24929940/36582643-369f2348-18ad-11e8-990a-856509b73b45.png)
![_20180223152017](https://user-images.githubusercontent.com/24929940/36582672-512eee8c-18ad-11e8-8519-b247082e794e.png)

**Comment by wuzhizhan** [comment]
最新版本只支持2016.1以上
