### ISSUE TITLE
DAO 接口方法返回类型提示问题 (ps: 不影响正常使用 )

### ISSUE THREAD

**Issue by luckylocode** [wuzhizhan/free-idea-mybatis#36]
当 mapper  里  resultType="map" 时，  接口方法 返回类型为  List<Map<String, String>>；
ide  会提示 result type  not match for ...... ；
也就是 默认的别名使用会出现错误提示。
![11111](https://user-images.githubusercontent.com/22515554/38713419-a395da88-3f03-11e8-8312-fcbfce377cf0.png)

**Comment by wuzhizhan** [comment]
fix
