### ISSUE TITLE
idea 2018.1 不工作

### ISSUE THREAD

**Issue by chao-luo** [wuzhizhan/free-idea-mybatis#38]
安装完插件后，也试了invalidate cache and restart, 但是仍然不能从dao interface 跳转到xml， 版本信息

_IntelliJ IDEA 2018.1 (Ultimate Edition)
Build #IU-181.4203.550, built on March 27, 2018
Subscription is active until August 31, 2018
JRE: 1.8.0_152-release-1136-b20 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.12.6_

**Comment by LoreYun** [comment]
我也遇到该问题了，xml可以跳转到 Mapper，但是Mapper跳转不到xml。

IntelliJ IDEA 2018.1.2 (Ultimate Edition)
Build #IU-181.4668.68, built on April 24, 2018
JRE: 1.8.0_152-release-1136-b29 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

**Comment by wuzhizhan** [comment]
@LoreYun 我开发的时候也出现过你这个问题，但后来不知怎么就正常了。我现在又复原不了2333

**Comment by kilodleif** [comment]
![image](https://user-images.githubusercontent.com/18283234/39617376-0eeb4d5e-4fb2-11e8-9c62-9811cc08d00a.png)
重新索引一下就好了。

**Comment by chao-luo** [comment]
我发现原来这个只识别以Mapper结尾的class和xml，这个支持更多？

**Comment by chao-luo** [comment]
class的名字是xxxDao.java, xml名字是xxxDao.xml， 发现这个就不行。

**Comment by liyongjun1** [comment]
@LoreYun @chao-luo 卸载掉现在的插件，重新安装一遍就继续生效了
