### ISSUE TITLE
Autowired error fix

### ISSUE THREAD

**Issue by syhily** [wuzhizhan/free-idea-mybatis#4]
<img width="291" alt="snapshot" src="https://cloud.githubusercontent.com/assets/1761698/14963700/7fff739c-10d7-11e6-8c68-0f39be0a55e4.png">
Like above.

**Comment by syhily** [comment]
I thought that I could work on this issue.

**Comment by wuzhizhan** [comment]
@syhily  没看明白这句英文。
What does this sentence mean？(I thought that I could work on this issue.)

**Comment by syhily** [comment]
XD, sorry for my poor english.

**Comment by hqs0417** [comment]
@syhily Good job! Are you working on this issue?

**Comment by fengyunhe** [comment]
This maybe about spring beans detector of idea.

**Comment by wuzhizhan** [comment]
I think it's because you doesn't write @Repository annotation on you Dao class

**Comment by CodeLieutenant** [comment]
写上@Repository是可以解决这个问题的。但是像，mybatis中生成的dao是可以不写@repository的，如果不写，就会出现导入错误。实际上通过（MyBatis Generator）自动生成的dao文件都是没有@repository这个注解的。弱弱问一下，除了手动加上@repository这个标记，还有其他办法吗，你是怎么做的呢

**Comment by wuzhizhan** [comment]
@CodeLieutenant  不写@Repository红色警告是idea本身的功能.我个人还是建议如果是DAO就加上这个注解
