### ISSUE TITLE
springboot RestuleType不能解析type-aliases-package的配置

### ISSUE THREAD

**Issue by zl7261** [wuzhizhan/free-idea-mybatis#61]
application中配置
 type-aliases-package: path
在XML中直接使用类名报红,实际使用没有问题

springBoot:    2.0.4
mybatis-spring-boot-starter:   1.3.2

**Comment by shuaicj** [comment]
遇到了相同问题

**Comment by shuaicj** [comment]
<img width="501" alt="Screen Shot 2019-06-27 at 10 28 57" src="https://user-images.githubusercontent.com/5753437/60233083-7f218200-98d1-11e9-8628-815061c58f0d.png">

排查了一下，主要由下面的第二个inspection所引起：
<img width="566" alt="Screen Shot 2019-06-27 at 10 27 58" src="https://user-images.githubusercontent.com/5753437/60233111-98c2c980-98d1-11e9-8c11-c594fc64075c.png">

@wuzhizhan

**Comment by wuzhizhan** [comment]
主要是mybatis没很好的读取application的内容，本人目前也比较忙，天天９９６，累积福报。
